trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

 - script: 
    cd Frontend
    npm install
  displayName: "Install dependencies"


  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: 'npm | "$(Agent.OS)"'
      path: $(Build.SourcesDirectory)/node_modules
    displayName: "Cache node_modules"

  - script: npm run build
    displayName: "Build project"

  - script: npm run test
    continueOnError: true
    displayName: "Run tests"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/build"
      ArtifactName: "build"
      publishLocation: "container"
    displayName: "Publish Build Artifacts"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/build"
      Contents: "**"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/build"
    displayName: "Copy build output to artifacts directory"
